In [1]:
#creating the matrix
def create_matrix():
  M = np.zeros([8,8] , dtype = int)
  for i in range(3):
   start_pos = i%2
   for j in range(start_pos,8,2):
     M[i][j]=1
    
  for i in range(5,8):
    start_pos = i%2
    for j in range(start_pos,8,2):
      M[i][j]=2
  
  return M

In [2]:
import numpy as np
# calculating each feature value of a board state for a target function
def feature_list(M):
  X = np.zeros(7,dtype = float)
  X[0] = 1

  for i in range(8):
    for j in range(8):
      if M[i][j]==1 or M[i][j]==3:
        if M[i][j]==1:
          X[1]+=1
        else :
          X[3]+=1
        
        if i+1 < 8 and j-1 >= 0 and ( M[i+1][j-1]==2 or M[i+1][j-1]==4) and i-1 >= 0 and j+1 < 8 and M[i-1][j+1]==0:
          X[6]+=1
        elif i+1 < 8 and j+1 < 8 and ( M[i+1][j+1]==2 or M[i+1][j+1]==4) and i-1 >= 0 and j-1 >= 0 and M[i-1][j-1]==0:
          X[6]+=1
        elif i-1 >= 0 and j+1 < 8 and M[i-1][j+1]==4 and i+1 < 8 and j-1 >= 0 and M[i+1][j-1]==0:
          X[6]+=1
        elif i-1 >= 0 and j-1 >= 0 and M[i-1][j-1]==4 and i+1 < 8 and j+1 < 8 and M[i+1][j+1]==0:
          X[6]+=1

      if M[i][j]==2 or M[i][j]==4:
        if M[i][j]==2:
          X[2]+=1
        else :
          X[4]+=1
        
        if i-1 >= 0 and j-1 >= 0 and ( M[i-1][j-1]==1 or M[i-1][j-1]==3) and i+1 < 8 and j+1 < 8 and M[i+1][j+1]==0:
          X[5]+=1
        elif i-1 >= 0 and j+1 < 8 and ( M[i-1][j+1]==1 or M[i-1][j+1]==3) and i+1 < 8 and j-1 >= 0 and M[i+1][j-1]==0:
          X[5]+=1
        elif i+1 < 8 and j+1 < 8 and M[i+1][j+1]==3 and i-1 >= 0 and j-1 >= 0 and M[i-1][j-1]==0:
          X[5]+=1
        elif i+1 < 8 and j-1 >= 0 and M[i+1][j-1]==3 and i-1 >= 0 and j+1 < 8 and M[i-1][j+1]==0:
          X[5]+=1
  
  return X


In [3]:
 #Function to calculate Score
def total_score(W,M):
  X = feature_list(M)
  sum = 0
  for i in range(7):
    sum += W[i]*X[i]
  return sum

In [4]:
def check_allzero(M):
  iszero = 1

  for i in range(8):
    for j in range(8):
      if M[i][j] != 0:
        iszero = 0
        return iszero
  
  return iszero

In [5]:
def choose_move(ans,M,W):

  iszero = check_allzero(ans)
  if iszero == 0 :
    x1 = total_score(W,ans)
    x2 = total_score(W,M)

    if x2 > x1 :
      for i in range(8):
        for j in range(8):
          ans[i][j]=M[i][j]
  else :
    for i in range(8):
      for j in range(8):
        ans[i][j]=M[i][j]

In [6]:
def best_move(x,j,temp,ans,W,l,dir):

  if x==0 and temp[x][j]==2 :
    temp[x][j]=4
  if x==7 and temp[x][j]==1 :
    temp[x][j]=3
  if dir == 1:
     choose_move(ans,temp,W)
  else :
        l.append(temp)

In [7]:

def killing_move(M , i , j , W ,dir,p, ans,l):
  
  x1 = i + dir*1
  x2 = i + dir*2

  opp1 = 2 if dir == 1 else 1
  opp2 = 4 if dir == 1 else 3

  if x2 < 8 and x2 > 0 and j-2 >=0 and ( M[x1][j-1]==opp1 or M[x1][j-1] == opp2) and M[x2][j-2] == 0:
      temp = M.copy()
      temp[i][j]=temp[x1][j-1]=0
      temp[x2][j-2]=M[i][j]
      best_move(x2,j-2,temp,ans,W,l,dir)
      killing_move(temp,x2,j-2,W,dir,p,ans,l)
    
  if x2<8 and x2 >= 0 and j+2<8 and (M[x1][j+1]==opp1 or M[x1][j+1]==opp2) and M[x2][j+2]==0:
      temp = M.copy()
      temp[i][j]=temp[x1][j+1] = 0
      temp[x2][j+2]=M[i][j]
      choose_move(ans,temp,W)
      best_move(x2,j+2,temp,ans,W,l,dir)
      killing_move(temp,x2,j+2,W,dir,p,ans,l)

  if M[i][j]==p+2:

    x1 = i - dir*1
    x2 = i - dir*2

    if x2 < 8 and x2 > 0 and j-2 >=0 and ( M[x1][j-1]==opp1 or M[x1][j-1] == opp2) and M[x2][j-2] == 0:
      temp = M.copy()
      temp[i][j]=temp[x1][j-1]=0
      temp[x2][j-2]=M[i][j]
      best_move(x2,j-2,temp,ans,W,l,dir)
      killing_move(temp,x2,j-2,W,dir,p,ans,l)
    
  if x2<8 and x2 >= 0 and j+2<8 and (M[x1][j+1]==opp1 or M[x1][j+1]==opp2) and M[x2][j+2]==0:
      temp = M.copy()
      temp[i][j]=temp[x1][j+1] = 0
      temp[x2][j+2]=M[i][j]
      best_move(x2,j+2,temp,ans,W,l,dir)
      killing_move(temp,x2,j+2,W,dir,p,ans,l)



In [8]:
def normal_move(M,i,j,W,dir,p,ans,l):
  
  x1 = i + dir*1
  x2 = i - dir*1

  if x1 < 8 and x1 >= 0 and j-1 >=0 and M[x1][j-1]==0:
    temp = M.copy()
    temp[i][j]=0
    temp[x1][j-1]=M[i][j]
    best_move(x1,j-1,temp,ans,W,l,dir)
    
  if x1<8 and x1>=0 and j+1<8 and M[x1][j+1]==0:
    temp = M.copy()
    temp[i][j]=0
    temp[x1][j+1]=M[i][j]
    best_move(x1,j+1,temp,ans,W,l,dir)

  if x2>=0 and x2 < 8 and j+1<8 and M[i][j]==p+2 and M[x2][j+1]==0:
    temp = M.copy()
    temp[i][j]=0
    temp[x2][j+1]=M[i][j]
    best_move(x2,j+1,temp,ans,W,l,dir)

  if x2>=0 and x2 < 8 and j-1>=0 and M[i][j]==p+2 and M[x2][j-1]==0:
    temp = M.copy()
    temp[i][j]=0
    temp[x2][j-1]=M[i][j]
    best_move(x2,j-1,temp,ans,W,l,dir)

In [9]:
def program_move(M,W):
 
 ans = np.zeros([8,8], dtype = int)
 l=[]

 for i in range(8):
   for j in range(8):
     if M[i][j]!=1 and M[i][j]!=3:
       continue
     normal_move(M,i,j,W,1,1,ans,l)
     killing_move(M,i,j,W,1,1,ans,l)

 return ans 

In [10]:
def program_move_black(M,W):
 
 ans = np.zeros([8,8], dtype = int)
 l=[]

 for i in range(8):
   for j in range(8):
     if M[i][j]!=2 and M[i][j]!=4:
       continue
     normal_move(M,i,j,W,1,2,ans,l)
     killing_move(M,i,j,W,1,2,ans,l)

 return ans 

In [11]:
def random_move(M):
  ans = np.zeros([8,8], dtype = int)
  l = []

  for i in range(8):
    for j in range(8):
      if M[i][j]==2 or M[i][j]==4:
        normal_move(M,i,j,W,-1,2,ans,l)
        killing_move(M,i,j,W,-1,2,ans,l)
  
  return l

In [12]:
def random_move_white(M):
  ans = np.zeros([8,8], dtype = int)
  l = []

  for i in range(8):
    for j in range(8):
      if M[i][j]==1 or M[i][j]==3:
        normal_move(M,i,j,W,-1,1,ans,l)
        killing_move(M,i,j,W,-1,1,ans,l)
  
  return l

In [13]:
def update_weight(x1,x2,X,W):
  alpha = 0.1

  for i in range(7):
    W[i] = W[i] + alpha*(x2 - x1)*X[i]

In [14]:
def find_best(List):
  ans = List[0]

  for k in range(len(List)):
    M = List[k]
    x1 = total_score(W,ans)
    x2 = total_score(W,M)

    if x2 > x1 :
      for i in range(8):
        for j in range(8):
          ans[i][j]=M[i][j]
  return ans

In [17]:
import random as random
# plays a single game until one finishes
def play_game(M,W):
  while 1 > 0 :
    L=feature_list(M) #feature List stores values of x0 - x6 of intial state
    score1=total_score(W,M)
    next_move = program_move(M,W)
    iszero = check_allzero(next_move)

    if iszero == 1:
      print("\n 2 is winner \n ",M)
      update_weight(score1,-100,L,W)
      return ;
    
    M = next_move
    #print("\n turn 1 \n",M)
    move_list = random_move(M)

    if len(move_list) == 0:
      print("\n 1 is winner \n ",M)
      update_weight(score1,100,L,W)
      return ;

    length = len(move_list);
    x = random.randint(0,length-1)
    #M = find_best(move_list)
    M = move_list[x]
    #print("\n turn 2 \n",M)
    score2 = total_score(W,M)
    update_weight(score1,score2,L,W)
    # print('changed weights ',score1,score2,' \n',L,'\n weight :',W,'\n matrix is \n',move_list)

In [18]:
import numpy as np

#intialising the weights
W = np.ones(7,dtype=float)

#traing the data
iter = 2

for i in range(iter):
  M = create_matrix()
  print('weights : ',W,'\n')
  play_game(M,W)

print("final weights : ",W)

weights :  [1. 1. 1. 1. 1. 1. 1.] 


 2 is winner 
  [[4 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 4]]
weights :  [ -9.3898279   -1.15518725   1.23772237   0.4376568  -20.1653195
  -0.74320626   0.84061702] 


 1 is winner 
  [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 3 0 3 0 0 0 0]]
final weights :  [ 2.00180564 11.86996231 -7.69216402 32.61014737 17.9766812  14.66161364
 -3.44357136]
